Repository aspsptyd/terintegrasi-app, pull requests merged in 2023-06, with the labels that each got.

#4 Modify README ke-9 : Tambah informasi Versi 1.0
  README.md
Labels: Tech Debt

#5 Tech Debt : Penyesuaian Template untuk Informasi Versi serta fitur yang plug in didalamnya
  .env
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
Labels: Tech Debt

#6 New Feature : Integrasi Role User
  .env
  README.md
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/BerandaAdministratorController.php
  app/Http/Controllers/BerandaSiswaController.php
  app/Http/Controllers/BerandaStaffController.php
  app/Http/Controllers/BerandaWaliController.php
  app/Http/Kernel.php
  app/Http/Middleware/Administrator.php
  app/Http/Middleware/Siswa.php
  app/Http/Middleware/Staff.php
  app/Http/Middleware/Wali.php
  app/Models/User.php
  database/migrations/2023_06_03_173125_add_roles_to_users_table.php
  database/migrations/2023_06_03_173752_add_phone_number_to_users_table.php
  database/migrations/2023_06_03_173758_add_phone_number_verified_at_to_users_table.php
  resources/views/administrator/beranda_index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/siswa/beranda_index.blade.php
  resources/views/staff/beranda_index.blade.php
  resources/views/wali/beranda_index.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: new-feature

#9 Tech Debt : Penyesuaian Versi Template dan Versi Aplikasi
  .env
  resources/views/administrator/beranda_index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/app_sneat.blade.php
  resources/views/wali/beranda_index.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: tech-debt
